version: '3'

services:
  glpi:
    build: .
    ports:
      - "8181:80"

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: glpi
      MYSQL_USER: user-glpi
      MYSQL_PASSWORD: pass-glpi
